### ISSUE TITLE
Image not visible in Benchmark Wiki

### ISSUE THREAD

**Issue by nelsonic** [broofa/node-uuid#104]
When visiting: https://github.com/broofa/node-uuid/wiki/Benchmark
The image is not visible.
![node-uuid_wiki_benchmark_image-404](https://cloud.githubusercontent.com/assets/194400/6375905/38df1784-bd12-11e4-91bb-c9cf40f323cd.png) **404** when attempting to access it.

**Comment by broofa** [comment]
Thanks.  Deleted page, as it's pretty out of date.

**Comment by nelsonic** [comment]
Fair enough. I will run `node benchmark/benchmark.js` locally then. *Thanks*!
