### ISSUE TITLE
crypto API isn't used in node.js context

### ISSUE THREAD

**Issue by fedot** [broofa/node-uuid#108]
After commit 319dc6e2e75f8ff57e9e708e2187bdabba6ca86a, Node Crypto API isn't used anymore.

I'm not sure if this is critical as v4 is random or pseudo-random based (RFC advise on usage of cryptographic quality random numbers but doesn't require it in any way).

I'm not sure if this is something that planned to be fixed (`Math.random` is significally faster and this may be a good reason to keep it that way and not to use Crypto API by default).

As for now I'm using `options.rng` passing `function(){ return crypto.randomBytes(16) }` as random generator.

**Comment by fedot** [comment]
It's also important to note that current information in README is incorrect for a more that a year stating that "Cryptographically strong random # generation on supporting platforms" which is not.

Also docs on `options.rng` are not correct referencing "built-in generators" that no longer exists

**Comment by joepie91** [comment]
> I'm not sure if this is critical

It is, unfortunately. The random data being cryptographically secure, is what prevents malicious users from generating collisions.

The security of UUIDs is thus significantly worse when the random source isn't cryptographically secure - not just when generating random tokens (eg. e-mail verification), but also when, for example, creating UUIDs for items in the database. Depending on exact implementation, that could result in privilege escalation within the application.

I'd recommend using the [defunctzombie fork](https://github.com/defunctzombie/node-uuid) instead, as this version doesn't appear to be actively maintained anymore. The npm package name for that is `uuid`.

**Comment by coolaj86** [comment]
fixed
