### ISSUE TITLE
[CRITICAL] Unsafe fallback to Math.random

### ISSUE THREAD

**Issue by joepie91** [broofa/node-uuid#118]
__This is a critical issue, compromising the security of this module.__

In [this part of the code](https://github.com/broofa/node-uuid/blob/master/uuid.js#L38-L52), this module will fall back to Math.random, regardless of the environment.

This is unsafe, as the `crypto` module may not always be available in Node.js environments - Node.js may have been compiled without OpenSSL, or a past or future version of Node.js may be used that does not carry the module. In this case, it will silently fall back to poor-quality random data.

The correct behaviour in non-browser environments would be to throw an error, and refuse to continue, if no 'safe' random source can be obtained, and to let the system administrator fix their environment.

Ideally, in browser environments, it would be *allowed* to fall back to Math.random, but only if an `allowUnsafe` (or similar) flag were specified on usage. This means the behaviour is safe by default, but can still be run unsafely if old browsers absolutely must be supported, and cryptographically secure UUIDs are not required.

EDIT: Apparently the `crypto` usage is broken in all cases? Per #108.

**Comment by joepie91** [comment]
My current advice would be to use the [defunctzombie fork](https://github.com/defunctzombie/node-uuid) (on npm as `uuid`) instead of this module (which is on npm as `node-uuid`). It does not suffer from this issue.

**Comment by coolaj86** [comment]
fixed
