### ISSUE TITLE
babel throwing error on line 19

### ISSUE THREAD

**Issue by reharik** [broofa/node-uuid#119]
Hi, I have a module that uses node-uuid 1.4.3.  I'm compiling said module with babel 5.8.2 and the flag ignore: false.  The ignore flag has babel compile your dependencies or rather setting it to false does.  The reason I have this set to false is because I have modules of my own that are using some es6 stuff, they are required via github and so to run the top level module I need to compile my dependent modules too.
Unfortunately this is causing an error that looks like this:
```
node_modules/node-uuid/uuid.js:19
  if (typeof _global.require == 'function') {
                    ^
TypeError: Cannot read property 'require' of undefined
```

I'm not sure what's going on but if some one does it would be great if you could let me know.
Thanks,
Raif

**Comment by sergesemashko** [comment]
@reharik, did you find the solution? I have exactly the same error.
Thanks

**Comment by reharik** [comment]
yes and no, I found a work around and that is you can give babel a ignore list.  I'm just having to put all stuff that's causing babel to blow up in the ignore list.  There are a couple of things.

**Comment by sergesemashko** [comment]
just tried that and it works for me too. thanks

**Comment by coolaj86** [comment]
This should no longer require an ignore list.
