### ISSUE TITLE
v1 method keeps returning the same uuid over and over again

### ISSUE THREAD

**Issue by amirmohsen** [broofa/node-uuid#120]
I've been using this package for ages now and have never had this problem before.

If you look at this jsfiddle, when I use the v1 method, it keeps giving me the same number over and over again.

http://jsfiddle.net/amirmohsen/cLcpxddd/1/

I installed it via bower this time since I am using it in the browser. However, in the jsfiddle, I just copied and pasted it.

**Comment by broofa** [comment]
Working for me.

Are you sure it's the same # each time?   v1() ID's created at nearly the same time will look very similar.  I've attached a screenshot showing my results.  Notice only the 8th digit changes. 

![image](https://cloud.githubusercontent.com/assets/164050/9415372/c033d4d8-47f3-11e5-9ad0-4efb91defb69.png)

**Comment by broofa** [comment]
This is working for me as expected in Firefox, too.  Pending a recipe for reproducing you're issue, there's not much I can do here.   Please investigate further and let me know what you find.  E.g. consider using stepping thru the v1() method in the debugger to verify it's behavior...?
