### ISSUE TITLE
Allow me to patch the Security Vulnerability

### ISSUE THREAD

**Issue by coolaj86** [broofa/node-uuid#124]
@broofa, I know you're super busy. Please add me my copying and pasting this into your console and I'll update `node-uuid` to fix the security issue:

```
npm owner add coolaj86 node-uuid
```

Also, I'd be willing to **help manage issues** if you would **add me as a collaborator**.

1. Go to <https://github.com/broofa/node-uuid/settings/collaboration>
2. Type your password
3. Add `coolaj86`

Thanks!

Re: https://github.com/broofa/node-uuid/issues/122, https://github.com/broofa/node-uuid/issues/118, https://github.com/broofa/node-uuid/issues/108.

**Comment by broofa** [comment]
Done!

(And many thanks for taking this on!)

**Comment by heilage-nsk** [comment]
@coolaj86 
After last minor upgrade the uuid generation began to fail within browserify on browsers that do not support window.crypto (ie10 and older, opera 12, phantomjs 1.9). Why such breaking change was introduced without changing major version?

**Comment by coolaj86** [comment]
Let's open a new issue for this and take a look. We'll need to add a test for what conditions browserify is checking to make sure minor changes don't break it again in the future.

When you open the new issue please include any detail about the error or how to reproduce and I'll take a look asap.
