### ISSUE TITLE
Do we want to make it even faster?

### ISSUE THREAD

**Issue by coolaj86** [broofa/node-uuid#125]
I got curious and decided to rework the crazy 140 byte uuid generator to see if I could get it to be as fast as node-uuid.

I had to increase the filesize quite a bit in the end, but I ended up with something that's **twice as fast**.
I bet we could just use the pooling of crypto bytes and increase the speed of this module quite a bit (at the expense of a slight increase in uncollectible memory use).

https://gist.github.com/coolaj86/7e5ebb9a6708d0ebfc78

Not sure if that fits in with the goals of the project or not, but if so it wouldn't be a hard change.

**Comment by broofa** [comment]
Are there real-world cases where this perf difference matters?

I had a similar focus on perf when I first started this project, but later came to be of the opinion that uuid generation was sufficiently fast for most/all practical applications.  For example, how does the perf for creating a guide compare to the perf of the other operations typically associated with that, like saving to a DB?

Currently I'm of the mind that code clarity should take precedence (and also aware that node-uuid doesn't completely reflect that belief. :-) )
