### ISSUE TITLE
Version 1 doesn't seem to use MAC address

### ISSUE THREAD

**Issue by halt-hammerzeit** [broofa/node-uuid#130]
https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_.28MAC_address_.26_date-time.29
I didn't find any word "mac" in your source code other than "Mac Os X"

**Comment by coolaj86** [comment]
It's meant to also be able to run cross-platform and in the browser so it doesn't actually use the mac address.

**Comment by broofa** [comment]
Getting MAC address is problematic cross-platform so this lib uses a randomly generated node field, which is acceptable per RFC4122

**Comment by halt-hammerzeit** [comment]
Oh, ok, if it complies with RFC.
