### ISSUE TITLE
IE10: [SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()

### ISSUE THREAD

**Issue by phun-ky** [broofa/node-uuid#148]
Probably related to https://github.com/broofa/node-uuid/issues/134

Getting this error in IE10. Edge, Firefox and Chrome is fine.

**Comment by coolaj86** [comment]
Is crypto usable in IE10? Because if it's missing then... it's missing :-/

**Comment by coolaj86** [comment]
http://caniuse.com/#search=crypto

This shows only IE11+ have crypto support. You'd have to provide a custom random function. Perhaps something like https://www.npmjs.com/package/more-entropy

**Comment by phun-ky** [comment]
Sure, how do I let `node-uuid` use `more-entropy` then?

**Comment by coolaj86** [comment]
See https://github.com/broofa/node-uuid/blob/master/README.md#uuidv4options--buffer--offset
