### ISSUE TITLE
Re-export RNG functions

### ISSUE THREAD

**Issue by thpani** [broofa/node-uuid#89]
35aa0a21501843f65140a6e5ce39ea54c2762432 removes symbolic RNG exports `uuid.{mathRNG,nodeRNG,whatwgRNG}`, but they are still mentioned in [README.md](https://github.com/broofa/node-uuid/blob/master/README.md#uuidv4options--buffer--offset).

Rather than fixing the docs, I think re-exporting them would be preferable. For example, I would like to force `v4` to use the crypto RNG.

**Comment by coolaj86** [comment]
This is now being done, but not exposed as a "public" api.

Also, the check for existence of `crypto` is now working properly.

Thoughts?

**Comment by thpani** [comment]
Looks good, thanks!
