### ISSUE TITLE
QUESTION: there is a way to use uuid like ObjectId() in mongoDb

### ISSUE THREAD

**Issue by eriknyk** [broofa/node-uuid#91]
Sorry by this question but:

there is a way to use the uuid like ObjectId() in mongoDb

Regards.

**Comment by tjconcept** [comment]
If your question is; can I use a UUID as my primary key in a mongodb collection, then yes. It's as simple as saving your documents with `{ _id: uuid }`.

**Comment by broofa** [comment]
this question would receive a better response from the mongodb team.
