### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by neoziro** [broofa/node-uuid#92]
Bower.json is missing in the project, you should add one.

**Comment by julianxhokaxhiu** [comment]
+1 bower is quite different and is also useful to separate "frontend" stuff from "backend" stuff.

Can you please add it?

**Comment by AlexSanchezSTHLM** [comment]
Why do you need bower.json?
node-uuid is already available through Bower.
```
bower info node-uuid
```
Latest version 1.4.2 is available.

**Comment by neoziro** [comment]
I don't know why there is a debate of adding or not adding a bower.json, bower has a spec, every packages available on bower should have a bower.json. If you don't want to follow this rule I don't care, it was just a suggestion.

**Comment by broofa** [comment]
Hey gang, sorry for not chiming in earlier.  I'm not a Bower user so it's hard for me to opine on the pros and cons of this.  But it seems like most other major projects have bower.json support so I'm happy to take a pull request.

**Comment by maboiteaspam** [comment]
hi,

following http://bower.io/docs/creating-packages/ see PR #105 

Hope it s fine.

**Comment by broofa** [comment]
Closed in #105
